features:
- horse_id
- jockey_id
- trainer_id
- wakuban
- umaban
- sex
- age
- weight
- weight_diff
- tansyo_odds
- popularity
- impost
- agari
- race_type
- around
- course_len
- weather
- ground_state
- race_class
- place
- rank_3races
- prize_3races
- rank_5races
- prize_5races
- rank_10races
- prize_10races
- rank_1000races
- prize_1000races
params:
  metric: binary_logloss
  objective: binary
  random_state: 100
